name: ICS update checker
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Check update
        run: |
          deno run -A ./update.ts
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "bump: update ics file"
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "ics-update"
          delete-branch: true
          title: "Bump: Update ICS"
          body: ""
