name: Update checker
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  udd-check:
    uses: kamekyame/gh-actions-test/.github/workflows/udd-check.yml@main
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  ics-update-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Check update
        run: |
          deno run -A ./update.ts
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        if: ${{ always() }}
        with:
          commit-message: "feat: update ics file"
          token: ${{ steps.generate_token.outputs.token }}
          branch: "ics-update"
          delete-branch: true
          title: "feat: Update ICS"
          body: ""
